apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: update-openshift-manifest
  title: Update OpenShift Manifest
  description: Modify deployment.yaml in a GitHub repo
spec:
  owner: team:devops
  type: service

  parameters:
    - title: Repository Information
      required:
        - githubHost
        - githubOwner
        - repository
        - branch
        - targetBranch
      properties:
        githubHost:
          title: GitHub Host name
          type: string
          default: github.com
        githubOwner:
            title: GitHub Owner
            type: string
        repository:
            title: GitHub Repository
            type: string
        branch:
          title: Branch name
          type: string
          default: develop
        targetBranch:
          title: Target branch name
          type: string
          default: main
    - title: ResourceQuota values
      properties:
        limitsCpu:
          title: limits.cpu
          type: string
          default: "2"
        limitsMemory:
          title: limits.memory
          type: string
          default: "10Gi"
  steps:
    - id: fetch
      name: Fetch repository
      action: fetch:plain
      input:
        url: https://${{ parameters.githubHost }}/${{ parameters.githubOwner }}/${{ parameters.repository }}
        branch: main
        targetPath: ./target

    - id: replace-limits-cpu
      name: Update CPU Limit
      if: ${{ parameters.limitsCpu != '' }}
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: './target/manifests/resourcequota.yaml'
            matchRegex: true
            find: '(limits\.cpu:\s*)\d+'
            replaceWith: 'limits.cpu: ${{ parameters.limitsCpu }}'

    - id: replace-limits-memory
      name: Update Memory Limit
      if: ${{ parameters.limitsMemory != '' }}
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: './target/manifests/resourcequota.yaml'
            find: 'limits.memory'
            replaceWith: ${{ parameters.limitsMemory }}

    - id: publish
      name: Commit back
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.githubHost }}?owner=${{ parameters.githubOwner }}&repo=${{ parameters.repository }}
        branchName: ${{ parameters.branch }}
        targetBranchName: ${{ parameters.targetBranch }}
        title: "Title Update resourcequpta via RHDH"
        description: "Discription Update resourcequpta via RHDH"
        commitMessage: "Update resourcequpta via RHDH"
        gitAuthorName: "RHDH"
        forceFork: true
        sourcePath: ./target