apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: update-openshift-manifest
  title: Update OpenShift Manifest
  description: Modify deployment.yaml in a GitHub repo
spec:
  owner: team:devops
  type: service

  parameters:
    - title: Repository Information
      required:
        - repoUrl
        - branch
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
        branch:
          title: Git Branch
          type: string
          default: main

    - title: Resource Limit Values
      properties:
        requestsCpu:
          type: string
          title: requests.cpu
          default: "4"
        requestsMemory:
          type: string
          title: requests.memory
          default: 8Gi
        limitsCpu:
          type: string
          title: limits.cpu
          default: "3"
        limitsMemory:
          type: string
          title: limits.memory
          default: 10Gi
  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        url: ${{ parameters.repoUrl }}
        branch: ${{ parameters.branch }}

    - id: replace-values
      name: Replace values in ResourceQuota YAML
      action: roadiehq:utils:fs:replace
      input:
        files:
          - manifests/resourcequota.yaml
        replacements:
          - search: 'requests.cpu: "10"'
            replace: 'requests.cpu: "{{ parameters.requestsCpu }}"'
          - search: 'requests.memory: 10Gi'
            replace: 'requests.memory: {{ parameters.requestsMemory }}'
          - search: 'limits.cpu: "6"'
            replace: 'limits.cpu: "{{ parameters.limitsCpu }}"'
          - search: 'limits.memory: 12Gi'
            replace: 'limits.memory: {{ parameters.limitsMemory }}'

    - id: publish
      name: Commit back
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branch: ${{ parameters.branch }}
        commitMessage: "Update resourcequpta via RHDH"

