apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: update-openshift-manifest
  title: Update OpenShift Manifest
  description: Modify deployment.yaml in a GitHub repo
spec:
  owner: team:devops
  type: service

  parameters:
    - title: Repository Information
      required:
        - repoUrl
        - branch
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
        branch:
          title: Git Branch
          type: string
          default: main
    - title: ResourceQuota values
      properties:
        limitsCpu:
          title: limits.cpu
          type: string
          default: "2"
        limitsMemory:
          title: limits.memory
          type: string
          default: "10Gi"
  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        url: ${{ parameters.repoUrl }}
        branch: ${{ parameters.branch }}
        targetPath: ./target

    - id: replace-values
      name: Replace values in ResourceQuota YAML
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: './target/manifests/resourcequota.yaml'
            matchRegex: true
            find: 'limits\\.cpu:\\s*\\d+'
            replaceWith: ${{ parameters.limitsCpu }}
          - file: './target/manifests/resourcequota.yaml'
            matchRegex: true
            find: 'limits\\.memory:\\s*\\d+'
            replaceWith: ${{ parameters.limitsMemory }}

    - id: publish
      name: Commit back
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=nisyu04-org&repo=tenant-app-manifest
        branchName: develop
        targetBranchName: ${{ parameters.branch }}
        title: "Title Update resourcequpta via RHDH"
        description: "Discription Update resourcequpta via RHDH"
        commitMessage: "Update resourcequpta via RHDH"
        gitAuthorName: "RHDH"
        forceFork: true
        sourcePath: ./target