apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: update-openshift-manifest
  title: Update OpenShift Manifest
  description: Modify deployment.yaml in a GitHub repo
spec:
  owner: team:devops
  type: service

  parameters:
    - title: Repository Information
      required:
        - repoUrl
        - branch
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
        branch:
          title: Git Branch
          type: string
          default: main

    - title: Resource Limit Values
      properties:
        requestsCpu:
          type: integer
          title: requests.cpu
          default: 4
        limitsCpu:
          type: integer
          title: limits.cpu
          default: 3
  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        url: ${{ parameters.repoUrl }}
        branch: ${{ parameters.branch }}

    - id: replace-values
      name: Replace values in ResourceQuota YAML
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: 'manifests/resourcequota.yaml'
            matchRegex: true
            find: 'limits\.cpu:\s*"[^"]+"'
            replaceWith: "10"
    - id: publish
      name: Commit back
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branch: ${{ parameters.branch }}
        commitMessage: "Update resourcequpta via RHDH"

